### ISSUE TITLE
能不能写清楚依赖版本

### ISSUE THREAD

**Issue by alex-m78** [CaitinZhao/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection#16]

**Comment by StevenShi-23** [comment]
TF-1.12 with all other dependencies being latest versions works well for me. Alternatively, you may try my fork at https://github.com/StevenShi-23/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection

**Comment by DoFulangChen** [comment]
> TF-1.12 with all other dependencies being latest versions works well for me. Alternatively, you may try my fork at https://github.com/StevenShi-23/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection

thanks for your code, but I wonder whether you can provide pre-trained model or not? thanks a lot

**Comment by StevenShi-23** [comment]
@DoFulangChen Sure. You can find the model [here](https://github.com/StevenShi-23/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection/blob/master/model/PFA_00050.h5).

**Comment by DoFulangChen** [comment]
> @DoFulangChen Sure. You can find the model [here](https://github.com/StevenShi-23/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection/blob/master/model/PFA_00050.h5).

thank you sir, your comments are really helpful

**Comment by sairajk** [comment]
Hi @alex-m78 @StevenShi-23 and @DoFulangChen 

You can check my PyTorch implementation of this paper [here](https://github.com/sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection/tree/master).
