### ISSUE TITLE
The prompt does not have this file“train_pair.txt”, how to do

### ISSUE THREAD

**Issue by zwm19950414** [CaitinZhao/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection#6]

**Comment by creabob** [comment]
have u found it ? which folder should be written?

**Comment by creabob** [comment]
'''
    the from of 'train_pair.txt' is 
    img_path1 gt_path1\n
    img_path2 gt_path2\n 
    '''

see train.py line 29 .
